apiVersion: v2
name: traefik-reverse-proxy
description: Traefik reverse proxy to fan requests out to external services
type: application
version: 37.0.0
appVersion: "0.0.1"

dependencies:
  - name: traefik
    version: "37.0.0"
    repository: "https://traefik.github.io/charts"
